check db at the start to speedup importing processing

diff --git a/mysql_import b/mysql_import
--- a/mysql_import
+++ b/mysql_import
@@ -44,22 +44,25 @@ function in_array() {
   return 0
 }
 
-function import ()
-{
-    echo -n "Importing $1 into $DB ..."
+function checkdb() {
     # Check if database exists
-    err=`echo "quit" | mysql$OPTS $DB 2>&1`
+    err=`echo "quit" | mysql$OPTS $1 2>&1`
     if [ $? != 0 ]; then
         if echo "$err" | grep -q "Access denied"; then
-            echo -e "\nDATABASE $db EXISTS BUT USER $USER DOES NOT HAVE ACCESS TO IT, ABORTING"
+            echo -e "\nDATABASE $1 EXISTS BUT USER $USER DOES NOT HAVE ACCESS TO IT, ABORTING"
             exit
         fi
-        echo -n "[creating $DB]"
-        if ! echo "CREATE DATABASE $DB;" | mysql$OPTS 2>/dev/null ; then
-            echo -e "\nDATABASE $DB DOES NOT EXIST AND I FAILED TO CREATE IT, ABORTING"
+        echo -n "[creating $1]"
+        if ! echo "CREATE DATABASE $1;" | mysql$OPTS 2>/dev/null ; then
+            echo -e "\nDATABASE $1 DOES NOT EXIST AND I FAILED TO CREATE IT, ABORTING"
             exit
         fi
     fi
+}
+
+function import ()
+{
+    echo -n "Importing $1 into $DB ..."
     mysql$OPTS $DB <$1
     echo " done"
 }
@@ -67,6 +70,9 @@ function import ()
 if [ ! -z "$1" ]; then 
 	DB=$1; 
 fi
+
+checkdb $DB
+
 if [ ! -z "$2" ]; then 
 	tables=$(echo $2 | tr "," "\n")
 fi
@@ -79,7 +85,7 @@ if (($FULL != 0)); then
 	mysql$OPTS $DB < $FPATH
 else
 	if [ ! -z "$2" ]; then
-			import $TPATH/$2.sql
+		import "$TPATH/$2.sql"
 	else
 		for x in $TPATH/*.sql; do
 			import $x
